Sorting Algorithms/quicksort.cpp
Quicksort is added in sorting algorithms
=> quicksort added

GcdOfArray.py, LcmOfArray.py
GCD and LCM Implementation in Python for a Array. Beginner Friendly Mathematical Algorithm.
=> Basic Mathematical Algorithms

Sorting Algorithms/Heap Sort.cpp
Adding Heap Sort Algorithm in C++
=> Added Heap Sort in c++

Wilson's Theorem/README.md, Wilson's Theorem/Wilson'sTheorem.py
Prime number generation in a user specified range, using Wilson's Theorem.
=> Wilson's Theorem

Sorting Algorithms/Bucket_Sort.py
Added Bucket Sort algorithm - Python implementation
=> Bucket Sort Algo | Python

Greedy Algorithms/Activityselection.cpp
Created activity selection.cpp
=> Created activity selection.cpp

Sorting Algorithms/radixsort.cpp
The idea of Radix Sort is to do digit by digit sort starting from least significant digit to most significant digit. Radix sort uses counting sort as a subroutine to sort.
_with aid from geeksforgeeks.org_
=> Added C++ implementation of Radix sort

Sorting Algorithms/bucketsort.cpp
Added the cpp implementation of bucket sort
=> Added bucketsort.cpp

Binary Tree/BinaryTreeTraversal.cpp
#24 Created Binary Tree Traversal Program in Cpp
=> Created Binary Tree Traversal Program in Cpp

Sorting Algorithms/Python/ShellSort.py
=> changes in the text

String Manipulation/split.cpp
I added an algorithm in C++ to split a string into a vector of strings.
PR for Hacktoberfest!!
=> Add split string algorithm

Contributors.md, Graph/dfs_and_bfs.cpp
added graph traversals(bfs and dfs)
=> added graph traversals

Contributors.md, Graph Algorithms/fleury.cpp
Algorithm to find a Eulerian path in CPP
=> Add fleury algorithm

String Manipulation/pallindrome.cpp
Contributing to  https://github.com/memr5/Algorithms/
=> Pallindrome of String program added

Sorting Algorithms/C-CPP/bubble_sort.c
Issue #4 
Added Bubble Sort algorithm program in C
=> Added Bubble Sort program in C

Search Algorithms/C-CPP/BinarySearch.cpp
Issue #4 
Added C++ program for implementation of Binary Search
=> Added Binary Search Program in C++

String Matching/KMP.cpp
Added KMP String Searching algorithm in C++.
=> AddedKMP Algorithm for string matching in C++

String Manipulation/Python/occurence.py
Modified a frequency occurence chart to allow user input that will create a dictionary output with the occurence of characters, upper and lower case are seperate instances in this, as well as whitespaces.  Punctuation was also recognized.  Hopefully the documentation in the code helps explain the process well enough.
=> Adding Frequency Occurence to Str manipulation/Python

Contributors.md, Sorting Algorithms/php/Quick_Sort.php
=> added quick sort for PHP language

Search Algorithms/Java/LinearSearch.java
located in Sorting Algorithms/Java/
=> Added Linear search in Java

Dynamic Programming/Golombsequence.cpp
=> created golomb sequence

Search Algorithms/Python/breath-first-search.py
Added new Breath search algorithm in the tree.
=> added search algorithm

Search Algorithms/C-CPP/BinarySearch.cpp
added instruction for entering the array elements in ascending order only.
=> added commit by Raunakk02

Search Algorithms/C-CPP/LinearSearch.c
Issue #51 
Added Linear Search Program In C language
=> Added Linear Search Program in C

Search Algorithms/Golang/go.mod, Search Algorithms/Golang/linear/LinearSearch.go, Search Algorithms/Golang/main.go
Added Linear search algorithm in go! Issue #51
=> Added Golang linear search algorithm.

Search Algorithms/C-CPP/BinarySearch.c
Issue #51 
Added Binary Search Program In C Language
=> Added Binary Search Program in C

Search Algorithms/Python/jump_search.py, Sorting Algorithms/Python/merge_sort.py
I have added the jump search algo using python. I have used **math** module in this file. This code accepts a sorted array and the element that is needed to be searched and returns the index of the element of found.
=> Added jump_search in python

Search Algorithms/Ruby/LinearSearch.rb
=> linear search ruby

Graph Algorithms/Cycle in undirected Graph.cpp
added Cycle detection in undirected Graph in c++
=> Create Cycle in undirected Graph.cpp

Search Algorithms/Java/InterpolationSearch.java
Issue #51
Added Interpolation Search Program In Java Language.
=> Added Interpolation Search  Program in Java

Dynamic Programming/gcd.cpp
In this I use the DP approach to calculate Greatest common devisor.
=> create Greatest common divisor problem using DP

Sorting Algorithms/Java/InsertionSort.java, Sorting Algorithms/Java/SelectionSort.java
=> added InsertionSort

Sorting Algorithms/Java/HeapSort.java
=> added HeapSort

Dynamic Programming/longestcommonsubsequence.cpp
#4 
This code is using Dynamic Programming Approach
=> Longest Common Subsequence

Sorting Algorithms/C-CPP/heap_sort.c
Issue #4
Added Heap Sort In C Language
=> Added Heap Sort In C Language

Search Algorithms/C-CPP/jumpSearch.cpp
=> added jumpSearch.cpp

String Manipulation/cifracesar.c, String Manipulation/led_string.c
Input example:
1
VQREQFGT
2
Output example:
TOPCODER
=> Cesar cipher with string

Search Algorithms/CSharp/linearSearch.cs
Linear search of an array for c#
=> Add Linear Search C#

Sorting Algorithms/Python/wiggle_sort.py
This a reorganizing sorting method written in python.
=> wiggle_sort.py

Contributors.md, String Manipulation/Python/check_if_is_palindrome.py
An algorithm to check if a word is palindrome
=> check_if_is_palindrome.py

Mathematical Algorithms/Kotlin/IsPrime.kt
Kotlin program to check if a number is prime
=> kotlin is prime

Contributors.md, Sorting Algorithms/Python/insertion.py
my own insertion sort code in python
happy coding :)
=> my own insertion sort code in python

Dynamic Programming/n-queen.cpp
Add this file to the repository, this contains the c++ code for  the N-Queen problem
=> Add N-Queen problem
